config/routes.rb
Rails.application.routes.draw do

  resources :counters
  get 'talk_tabs', to: 'talk_tabs#index'
  # get 'admin/index'

  # get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end


  root to: 'experiments#index'

  resources :column_meta
  resources :label_meta
  resources :services  do
    member do
      put 'access_token', to: 'services#updateAccessToken'
    end
  end

  resources :labels, except: [:update] do
    member do
      post 'add_props_and_indices', to: 'labels#addPropsAndIndices'
    end
  end

  resources :buckets, only: [:new, :create, :edit, :show, :update, :destroy] do
    member do
      put 'copy_bucket', to: 'buckets#copyBucket'
    end
  end
  resources :services
  
  # resources :users, only: [:new, :create, :edit, :update, :destroy]
  resources :users do
    member do
      get :info
    end
  end
  resources :authorities
  resources :s2ml_apps
	resources :s2loader_jobs
  resources :s2admin_demos do
    member do
      get :demo
      get :default_id
    end
  end
  resources :experiments do
    member do
      get :detail
      post :modular
    end
  end

  post 'buckets/validate/request_body', to: 'buckets#validateRequestBody'

  get 'queries/visualize'

  post 'queries/partial_graph', to: 'queries#partialGraph'

  post 'queries/call_graph', to: 'queries#callGraph'

  get 'labels/check/:label_name', to: 'labels#check'

  get 'buckets/check/:impression_id', to: 'buckets#check'

  get 's2graph', to: 'services#index'

  get 's2counter', to: 'counters#index'

  get 'users', to: 'users#index'

  get 'access', to: 'authorities#index'

  get 's2ab', to: 'experiments#index'

  post 's2ab/:access_token/ratio-update-all', to: 'experiments#ratioUpdateAll'

  get 's2ab/:access_token/list(/:experiment_name)', to: 'experiments#list'

  get 's2ml', to: 's2ml_apps#index'

  get 's2ml_apps/:id/disable', to: 's2loader_jobs#disable'

  get 's2ml_apps/:id/enable', to: 's2loader_jobs#enable'

  get 's2loader', to: 's2loader_jobs#index'

  get 's2loader_jobs/:id/test', to: 's2loader_jobs#test'

  get 's2loader_jobs/:id/disable', to: 's2loader_jobs#disable'

  get 's2loader_jobs/:id/enable', to: 's2loader_jobs#enable'

  get 'demos', to: 's2admin_demos#index'

  get 'demos/:id/demo', to: 's2admin_demos#demo'

  get 'demos/update_descriptions', to: 's2admin_demos#update_descriptions'

  get 'demos/s2graph', to: 's2admin_demos#index'

  get 'demos/s2counter', to: 's2admin_demos#demo_counter.html.haml'

  get 'demos/talk-channel', to: 'talk_tabs#index'

  get 'links', to: 'links#list'

  get 'servers', to: 'servers#index'

  put 'servers/:server/:status', to: 'servers#toggle_health'

  get 'servers/load', to: 'servers#high_loads'

  get 'servers/latency', to: 'servers#high_latencies'
end

app/models/service.rb
class Service < ActiveRecord::Base
  has_many :labels
  has_many :service_columns
  has_many :experiments
  has_many :authorities

  def src_service
    Label.find_by src_service_id: id
  end

  def tgt_service
    Label.find_by tgt_service_id: id
  end
end

app/controllers/services_controller.rb
require 'htable'
class ServicesController < ApplicationController

  before_action :set_service, only: [:show, :edit, :update, :destroy, :updateAccessToken]
  before_action :set_active

  # GET /services
  def index
    user = User.find(session[:user_id])
    @authority = user.authority
    if @authority == 'master'
      @services = Service.all.order(:service_name)
    else
      authorities = Authority.where(user_id: session[:user_id]).select("service_id")
      @services = Service.where(id: authorities).order(:service_name)
    end
  end

  # GET /services/1
  def show
    # @service_columns = ServiceColumn.joins(:column_metas).where(service_id: @service.id).select("service_columns.*, column_metas.*")
    @service_columns = ServiceColumn.joins('LEFT OUTER JOIN column_metas ON column_metas.column_id = service_columns.id')
    .where(service_id: @service.id)
    .select("service_columns.*, column_metas.id as meta_id, column_metas.name, column_metas.column_id, column_metas.seq, column_metas.data_type")

    @labels = Label.where(service_id: @service.id)
    createService = {"serviceName" => @service.service_name, "hTableName" => @service.hbase_table_name, "preSplitSize" => @service.pre_split_size}
    if @service.hbase_table_ttl != nil
      createService["hTableTTL"] = @service.hbase_table_ttl
    end
    createServiceCURL = "curl -XPOST localhost:9000/graphs/createService -H 'Content-Type: Application/json' -d '\n#{JSON.pretty_generate(createService)}\n'"
    @createCURLs = createServiceCURL
    @labels.each do | label |
      # curl -XPOST localhost:9000/graphs/createLabel -H 'Content-Type: Application/json' -d '
      # {
      #     "label": "user_article_liked",
      #     "srcServiceName": "s2graph",
      #     "srcColumnName": "user_id",
      #     "srcColumnType": "long",
      #     "tgtServiceName": "s2graph_news",
      #     "tgtColumnName": "article_id",
      #     "tgtColumnType": "string",
      #     "indices": [], // _timestamp will be used as default
      #     "props": [],
      #     "serviceName": "s2graph_news"
      # }
      # '
      labelPostfix = label.label.split("_").last
      next if (labelPostfix == "counts" || labelPostfix == "topK")
      labelMetas = LabelMetum.where(label_id: label.id)
      labelIndices = LabelIndex.where(label_id: label.id).order(seq: :asc)

      props = labelMetas.map do | meta |
        {"name" => meta.name, "defaultValue" => meta.default_value, "dataType" => meta.data_type}
      end


      indices = labelIndices.map do | index |
        logger.error(index.meta_seqs)
        prop_names = index.meta_seqs.split(",").map do |meta_seq|
          meta_seq = meta_seq.to_i
          if meta_seq == 0
            "_timestamp"
          elsif meta_seq == -5
            "_to"
          elsif meta_seq == -8
            "_from_hash"
          else
            labelMetas.where(seq: meta_seq).first.name
          end
        end
        {"name" => index.name, "propNames" => prop_names}
      end
      createLabel = {"label" => label.label, "srcServiceName" => Service.find(label.src_service_id).service_name, "srcColumnName" => label.src_column_name, "srcColumnType" => label.src_column_type,
      "srcServiceName" => Service.find(label.src_service_id).service_name, "srcColumnName" => label.src_column_name, "srcColumnType" => label.src_column_type,
      "indices" => indices, "props" => props, "serviceName" => Service.find(label.service_id).service_name,
      "consistencyLevel" => label.consistency_level, "hTableName" => label.hbase_table_name}
      if label.is_directed == 1
        createLabel["isDirected"] = "true"
      else
        createLabel["isDirected"] = "false"
      end

      if label.hbase_table_ttl != nil
        createLabel["hTableTTL"] = label.hbase_table_ttl
      end

      createLabelCURL = "curl -XPOST localhost:9000/graphs/createLabel -H 'Content-Type: Application/json' -d '\n#{JSON.pretty_generate(createLabel)}\n'"
      @createCURLs = @createCURLs + "\n\n" + createLabelCURL
    end
    
  end

  # GET /services/new
  def new
    user = User.find(session[:user_id])
    @authority = user.authority
    if @authority != "master" then
      head :forbidden
    else
      @service = Service.new
    end
  end

  # GET /services/1/edit
  def edit
  end

  # POST /services
  def create
    @service = Service.new(service_params)

    result = HTable.createTable(@service.cluster, @service.hbase_table_name, @service.pre_split_size, @service.hbase_table_ttl, nil)
    if result
      if @service.save
        redirect_to services_url, notice: 'Service was successfully created.'
      else
        render :new
      end
    else
      render :new
    end
  end

  # PATCH/PUT /services/1
  def update
    if @service.update(service_params)
      redirect_to @service, notice: 'Service was successfully updated.'
    else
      render :edit
    end
  end

  def updateAccessToken
    if @service.update(access_token: params[:access_token])
      result = Hash["status" => "success"]
      render json: result.to_json
    else
      result = Hash["status" => "fail"]
      render json: result.to_json
    end
  end


  # DELETE /services/1
  def destroy
    @service.destroy
    redirect_to services_url, notice: 'Service was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service
      @service = Service.find(params[:id])
      has_authority
    end

    def has_authority
      user = User.find(session[:user_id])
      @authority = user.authority
      if @authority != "master" then
        authorities = Authority.where(user_id: session[:user_id], service_id: @service.id)
        if authorities.size <= 0
          head :forbidden
        end
      end
    end

    # Only allow a trusted parameter "white list" through.
    def service_params
      params.require(:service).permit(:service_name, :access_token, :cluster, :hbase_table_name, :pre_split_size, :hbase_table_ttl)
    end

    def set_active
      @active = "s2graph"
    end
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/services/_form.html.haml
= simple_form_for @service, html: { name: "service-form", onsubmit: "return validateServiceForm()"} do |f|
  = f.error_notification


  .form-wrap
    .form-inputs.form
      = f.input :service_name, label: "service name", required: true
      = f.input :access_token, label: "access token", required: true, disabled: true, input_html: { name: 'service[access_token_diabled]', id: "service_access_token_disabled"}
      = f.input :access_token, as: :hidden, id: "access_token_input", input_html: { name: 'service[access_token]'}
      = f.input :cluster, :label => "cluster", disabled: true, input_html: { value: APP_CONFIG['cluster']}, required: true, input_html: { value: APP_CONFIG['cluster'], name: 'service[cluster_disabled]'}
      = f.input :cluster, as: :hidden, input_html: { value: APP_CONFIG['cluster']}
      = f.input :hbase_table_name, label: "hbase table name", required: true
      = f.input :pre_split_size, label: "pre split size"
      = f.input :hbase_table_ttl, label: "hbase table ttl"
    .form-actions
      = f.button :submit, :class => 'btn btn-primary'

app/views/services/edit.html.haml
%h3 EDITING SERVICE
#s2admin-form-layout
  = render 'form'
  = link_to 'Show', @service
  |
  \#{link_to 'Back', services_path}

app/views/services/index.html.haml
%p#notice= notice
%h3 S2GRAPH
#s2admin-contents-layout
  .row
    .col-md-12.btn-create
      - if @authority == 'master'
        = button_to 'CREATE SERVICE', new_service_path, class: "btn btn-primary", method: :get
  .row
    %div{class: "form-group pull-right"}
      %input{type:"text", class:"search form-control", placeholder:"search"}
    %span{class: "counter pull-right"}
    %table.table.table-hover.tablesorter.results
      %thead
        %tr
          %th ID
          %th SERVICE NAME
          %th ACCCESS TOKEN
          %th HBASE TABLE NAME
          %th PRE-SPLIT SIZE
          %th HBASE TABLE TTL
      %tbody
        - @services.each do |service|
          %tr{onClick: "location.href='/services/#{service.id}'", style: "cursor:pointer;"}
            %td= service.id
            %td= service.service_name
            %td= service.access_token
            %td= service.hbase_table_name
            %td= service.pre_split_size
            %td= service.hbase_table_ttl
            / %td= link_to 'Show', service
            / %td= link_to 'Edit', edit_service_path(service)
            / %td= link_to 'Destroy', service, method: :delete, data: { confirm: 'Are you sure?' }
  .row
    .col-md-12.btn-create
      - if @authority == 'master'
        = button_to 'CREATE SERVICE', new_service_path, class: "btn btn-primary", method: :get

app/views/services/new.html.haml
%h3 CREATE SERVICE
#s2admin-form-layout
  = render 'form'
  = link_to 'Back', services_path

:javascript
  $(document).ready(function() {
    var uuid = generateUUID()
    $("#service_access_token").val(uuid)
    $("#service_access_token_disabled").val(uuid)
  });

app/views/services/show.html.haml
%p#notice= notice
%div{:class => "row"}
  .col-md-12
    .row
      .col-md-12#service-title
        %span
          = @service.service_name
        %span{id: "service-id"}
          = @service.id
    %hr
    .row.service-div
      .row
        .col-md-12.contents-div
          - if @service.access_token.nil?
            %div{class: "access-token-warning", role: "alert"} access_token is missing.
            %button{type: "button", class: "btn btn-primary btn-sm", id: "gen-access-token", "data-toggle" => "modal", "data-target" => "#gen-access-token-modal"} generate
          -else
            access token : #{@service.access_token}
          %div{id: "gen-access-token-modal", class: "modal fade", "role" => "dialog"}
            %div{class: "modal-dialog modal-sm modal-access-token"}
              %div{class: "modal-content"}
                %div{class: "modal-header"}
                  %h6{class: "modal-title"}Generate ACCESS_TOKEN
                %div{class: "modal-body"}
                  %div{id: "uuid"}
                %div{class: "modal-footer"}
                  %button{type: "button", class: "btn btn-primary btn-sm", id: "btn-save-access-token"}Save
                  %button{type: "button", class: "btn btn-default btn-sm", "data-dismiss" => "modal"}Close
      .row
        .col-md-12.contents-div cluster : #{@service.cluster}
      .row
        .col-md-12.contents-div hbase table name : #{@service.hbase_table_name}
      .row
        .col-md-12.contents-div pre split size : #{@service.pre_split_size}
      .row
        .col-md-12.contents-div hbase table ttl : #{@service.hbase_table_ttl}
      .row
        .col-md-12.contents-div
          %button{type: "button", class: "btn btn-primary btn-sm", id: "btn-show-create-service", "data-toggle" => "modal", "data-target" => "#show-create-service-modal"} SHOW CREATE SERVICE & LABELS
          %div{id: "show-create-service-modal", class: "modal fade", "role" => "dialog"}
            %div{class: "modal-dialog modal-lg modal-create-service"}
              %div{class: "modal-content"}
                %div{class: "modal-header"}
                  %h6{class: "modal-title"} SHOW CREATE SERVICE & LABELS
                %div{class: "modal-body"}
                  %pre #{@createCURLs}
                %div{class: "modal-footer"}
                  %button{type: "button", class: "btn btn-default btn-sm", "data-dismiss" => "modal"}Close
    %hr
    .row
      .col-md-12.btn-create
        = button_to 'CREATE LABEL', new_label_path, class: "btn btn-primary", method: :get
    .row
      %div{class: "form-group pull-right"}
        %input{type:"text", class:"search form-control", placeholder:"search"}
      %span{class: "counter pull-right"}
      %table.table.table-hover.tablesorter.results
        %thead
          %tr
            %th{rowspan: 2} ID
            %th{rowspan: 2} LABEL NAME
            %th{colspan: 3} SOURCE
            %th{colspan: 3} TARGET
            %th{rowspan: 2} IS DIRECTED
            %th{rowspan: 2} HBASE TABLE NAME
            %th{rowspan: 2} HBASE TABLE TTL
            %th{rowspan: 2} META
            %th{rowspan: 2} INDEX
            %th{rowspan: 2} ADD PROPS&INDICES
          %tr
            %th SERVICE
            %th COL NAME
            %th COL TYPE
            %th SERVICE
            %th COL NAME
            %th COL TYPE

        %tbody
          - services = Service.all
          - metas = LabelMetum.where(label_id: @labels).order(id: :asc)
          - indices = LabelIndex.where(label_id: @labels).order(id: :asc)
          - for label in @labels
            %tr
              %td{onClick: "location.href='/labels/#{label.id}'", style: "cursor:pointer;"}= label.id
              %td{onClick: "location.href='/labels/#{label.id}'", style: "cursor:pointer;"}= label.label
              %td{onClick: "location.href='/labels/#{label.id}'", style: "cursor:pointer;"}= services.find(label.src_service_id).service_name
              %td{onClick: "location.href='/labels/#{label.id}'", style: "cursor:pointer;"}= label.src_column_name
              %td{onClick: "location.href='/labels/#{label.id}'", style: "cursor:pointer;"}= label.src_column_type
              %td{onClick: "location.href='/labels/#{label.id}'", style: "cursor:pointer;"}= services.find(label.tgt_service_id).service_name
              %td{onClick: "location.href='/labels/#{label.id}'", style: "cursor:pointer;"}= label.tgt_column_name
              %td{onClick: "location.href='/labels/#{label.id}'", style: "cursor:pointer;"}= label.tgt_column_type
              %td{onClick: "location.href='/labels/#{label.id}'", style: "cursor:pointer;"}= label.is_directed
              %td{onClick: "location.href='/labels/#{label.id}'", style: "cursor:pointer;"}= label.hbase_table_name
              %td{onClick: "location.href='/labels/#{label.id}'", style: "cursor:pointer;"}= label.hbase_table_ttl
              %td
                %button{type: "button", class: "btn btn-warning btn-sm", "data-toggle" => "modal", "data-target" => "##{label.label}-meta"} meta
              %td
                %button{type: "button", class: "btn btn-success btn-sm", "data-toggle" => "modal", "data-target" => "##{label.label}-index"} index
              %td
                =link_to "add prop&indices", edit_label_path(label), class: "btn btn-primary btn-sm"
                / %link_to{type: "button", class: "btn btn-primary btn-sm"}
      .row
        .col-md-12.btn-create
          = button_to 'CREATE LABEL', new_label_path, class: "btn btn-primary", method: :get
  - for label in @labels
    %div{id: "#{label.label}-meta", class: "modal fade", "role" => "dialog"}
      %div{class: "modal-dialog modal-lg"}
        %div{class: "modal-content"}
          %div{class: "modal-header"}
            %h4{class: "modal-title"}META
          %div{class: "modal-body"}
            %pre.contents-value.json-body= JSON.pretty_generate(metas.where(label_id: label.id).as_json)
          %div{class: "modal-footer"}
            %button{type: "button", class: "btn btn-default", "data-dismiss" => "modal"}Close
  - for label in @labels
    %div{id: "#{label.label}-index", class: "modal fade", "role" => "dialog"}
      %div{class: "modal-dialog modal-lg"}
        %div{class: "modal-content"}
          %div{class: "modal-header"}
            %h4{class: "modal-title"}INDEX
          %div{class: "modal-body"}
            %pre.contents-value.json-body= JSON.pretty_generate(indices.where(label_id: label.id).as_json)
          %div{class: "modal-footer"}
            %button{type: "button", class: "btn btn-default", "data-dismiss" => "modal"}Close