config/routes.rb
Rails.application.routes.draw do

  resources :counters
  get 'talk_tabs', to: 'talk_tabs#index'
  # get 'admin/index'

  # get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end


  root to: 'experiments#index'

  resources :column_meta
  resources :label_meta
  resources :services  do
    member do
      put 'access_token', to: 'services#updateAccessToken'
    end
  end

  resources :labels, except: [:update] do
    member do
      post 'add_props_and_indices', to: 'labels#addPropsAndIndices'
    end
  end

  resources :buckets, only: [:new, :create, :edit, :show, :update, :destroy] do
    member do
      put 'copy_bucket', to: 'buckets#copyBucket'
    end
  end
  resources :services
  
  # resources :users, only: [:new, :create, :edit, :update, :destroy]
  resources :users do
    member do
      get :info
    end
  end
  resources :authorities
  resources :s2ml_apps
	resources :s2loader_jobs
  resources :s2admin_demos do
    member do
      get :demo
      get :default_id
    end
  end
  resources :experiments do
    member do
      get :detail
      post :modular
    end
  end

  post 'buckets/validate/request_body', to: 'buckets#validateRequestBody'

  get 'queries/visualize'

  post 'queries/partial_graph', to: 'queries#partialGraph'

  post 'queries/call_graph', to: 'queries#callGraph'

  get 'labels/check/:label_name', to: 'labels#check'

  get 'buckets/check/:impression_id', to: 'buckets#check'

  get 's2graph', to: 'services#index'

  get 's2counter', to: 'counters#index'

  get 'users', to: 'users#index'

  get 'access', to: 'authorities#index'

  get 's2ab', to: 'experiments#index'

  post 's2ab/:access_token/ratio-update-all', to: 'experiments#ratioUpdateAll'

  get 's2ab/:access_token/list(/:experiment_name)', to: 'experiments#list'

  get 's2ml', to: 's2ml_apps#index'

  get 's2ml_apps/:id/disable', to: 's2loader_jobs#disable'

  get 's2ml_apps/:id/enable', to: 's2loader_jobs#enable'

  get 's2loader', to: 's2loader_jobs#index'

  get 's2loader_jobs/:id/test', to: 's2loader_jobs#test'

  get 's2loader_jobs/:id/disable', to: 's2loader_jobs#disable'

  get 's2loader_jobs/:id/enable', to: 's2loader_jobs#enable'

  get 'demos', to: 's2admin_demos#index'

  get 'demos/:id/demo', to: 's2admin_demos#demo'

  get 'demos/update_descriptions', to: 's2admin_demos#update_descriptions'

  get 'demos/s2graph', to: 's2admin_demos#index'

  get 'demos/s2counter', to: 's2admin_demos#demo_counter.html.haml'

  get 'demos/talk-channel', to: 'talk_tabs#index'

  get 'links', to: 'links#list'

  get 'servers', to: 'servers#index'

  put 'servers/:server/:status', to: 'servers#toggle_health'

  get 'servers/load', to: 'servers#high_loads'

  get 'servers/latency', to: 'servers#high_latencies'
end

app/models/label.rb
class Label < ActiveRecord::Base
  belongs_to :service
  has_many :label_metas
  has_many :label_index

end

app/controllers/labels_controller.rb
# coding: utf-8
require 'htable'
class LabelsController < ApplicationController
  before_action :set_label, only: [:show, :edit, :update, :destroy, :addPropsAndIndices]
  before_action :set_active
  skip_before_filter :authorize, only: [:check]

  class SourceColumnCreateError < StandardError
  end
  class TargetColumnCreateError < StandardError
  end
  class LabelAlreadyExist < StandardError
  end
  class PropertyAlreadyExist < StandardError
  end
  class IndexAlreadyExist < StandardError
  end


  # GET /labels
  def index
    user = User.find(session[:user_id])
    @authority = user.authority
    if @authority == 'master'
      @labels = Label.all
    else
      head :forbidden
    end
  end

  # GET /labels/1
  def show

  end

  # GET /labels/new
  def new
    id = params[:id]
    if !id.nil?
      @selected_service_name = Service.find(id).service_name
      @service_htable_name = Service.find(id).hbase_table_name
    end
    @label = Label.new
  end

  # GET /labels/1/edit
  def edit
    @hbase_table_name = @label.hbase_table_name
    @metas = LabelMetum.where(label_id: @label.id).order(id: :asc)
    @indices = LabelIndex.where(label_id: @label.id).order(id: :asc)
  end

  # GET /labels/check/s2graph_label
  def check
    label_name = params["label_name"]
    label = Label.where(label: label_name).take
    if label.nil?
      result = Hash["isAlreadyExist" => "false"]
      render json: result.to_json
    else
      result = Hash["isAlreadyExist" => "true"]
      render json: result.to_json
    end
  end

  # POST /labels
  def create

    service_id = label_params[:service_id]
    service = Service.find(service_id)
    service_name = service.service_name
    cluster = service.cluster

    label_name = label_params[:label]

    src_service_id = label_params[:src_service_id]
    src_column_name = label_params[:src_column_name]
    src_column_type = label_params[:src_column_type]

    tgt_service_id = label_params[:tgt_service_id]
    tgt_column_name = label_params[:tgt_column_name]
    tgt_column_type = label_params[:tgt_column_type]


    is_directed = label_params[:is_directed]
    consistency_level = label_params[:consistency_level]
    hbase_table_name = label_params[:hbase_table_name]
    hbase_table_ttl = label_params[:hbase_table_ttl] == nil ? service.hbase_table_ttl : label_params[:hbase_table_ttl]
    schema_version = label_params[:schema_version]
    is_async = label_params[:is_async]
    compressionAlgorithm = label_params[:compressionAlgorithm].nil? ? 'lz4' : label_params[:compressionAlgorithm]

    properties = label_params[:properties]
    indices = label_params[:indices]

    begin
      LabelsController.createLabel(service_id, label_name,
                        src_service_id, src_column_name, src_column_type,
                        tgt_service_id, tgt_column_name, tgt_column_type,
                        is_directed, consistency_level,
                        hbase_table_name, hbase_table_ttl, schema_version, is_async, compressionAlgorithm,
                        properties, indices)

    rescue ActiveRecord::RecordNotFound => e
      logger.error("Record not found. : #{e}")
      render_result("fail", "Record not found.")
    rescue SourceColumnCreateError => e
      logger.error("Source column create error. : #{e}")
      render_result("fail", "Source column create error.")
    rescue TargetColumnCreateError => e
      logger.error("Target column create error. : #{e}")
      render_result("fail", "Target column create error.")
    rescue LabelAlreadyExist => e
      logger.error("Label already exist. : #{e}")
      render_result("fail", "Label already exist.")
    rescue PropertyAlreadyExist => e
      logger.error("Property already exist. : #{e}")
      render_result("fail", "Property already exist.")
    rescue IndexAlreadyExist => e
      logger.error("Index already exist. : #{e}")
      render_result("fail", "Index already exist.")
    rescue HTable::HTableNameNotFound => e
      logger.error("Htable name not found. : #{e}")
      render_result("fail", "Htable name not found.")
    rescue HTable::HTableCreateError => e
      logger.error("Htable create error. : #{e}")
      render_result("fail", "Htable create error.")
    rescue => e
      render_result("fail", "Create label error. : #{e}")
    else
      render_result("success", "Label was created.")
    end
  end

  def self.createLabel(service_id, label_name,
                        src_service_id, src_column_name, src_column_type,
                        tgt_service_id, tgt_column_name, tgt_column_type,
                        is_directed, consistency_level,
                        hbase_table_name, hbase_table_ttl, schema_version, is_async, compressionAlgorithm,
                        properties, indices)
    service = Service.find(service_id)
    service_name = service.service_name
    cluster = service.cluster

    # source column 생성
    srcSc = LabelsController.service_column_find_or_insert(src_service_id, src_column_name, src_column_type, schema_version)
    if (srcSc.nil? || srcSc.column_type != src_column_type)
      # throw exception
      raise SourceColumnCreateError
    end
    # target column 생성
    tgtSc = LabelsController.service_column_find_or_insert(tgt_service_id, tgt_column_name, tgt_column_type, schema_version)
    if (tgtSc.nil? || tgtSc.column_type != tgt_column_type)
      # throw exception
      raise TargetColumnCreateError
    end

    ActiveRecord::Base.transaction do
      label = Label.where(label: label_name).take
      raise LabelAlreadyExist if !label.nil?
      # 새 라벨 생성
      # hbase table name 이 없으면 service의 hbase table name 사용
      hbase_table_name = (hbase_table_name.nil? || hbase_table_name == "") ? service.hbase_table_name : hbase_table_name

      label = Label.new(label: label_name, src_service_id: src_service_id, src_column_name: src_column_name, src_column_type: src_column_type,
        tgt_service_id: tgt_service_id, tgt_column_name: tgt_column_name, tgt_column_type: tgt_column_type,
        is_directed: is_directed, service_name: service_name, service_id: service_id, consistency_level: consistency_level,
        hbase_table_name: hbase_table_name, hbase_table_ttl: hbase_table_ttl, schema_version: schema_version, is_async: is_async, compressionAlgorithm: compressionAlgorithm)

      label.save!
      labelId = label.id

      LabelsController.addProps(labelId, properties)
      LabelsController.addIndices(labelId, indices, false)

      raise HTable::HTableNameNotFound if hbase_table_name.nil?

      hbase_table_ttl = hbase_table_ttl.nil? ? service.hbase_table_ttl : hbase_table_ttl
      result = HTable.createTable(cluster, hbase_table_name, service.pre_split_size, hbase_table_ttl, compressionAlgorithm)
      logger.error(result)

      raise HTable::HTableCreateError if result == false
    end # transaction end
  end

  def self.addProps(labelId, properties)

    LabelMetum.transaction do
      JSON.parse(properties).each do |property|
        propertyName = property["PROPERTY NAME"]
        existProp = LabelMetum.where(label_id: labelId, name: propertyName).take
        if (existProp.nil?)
          propertyType = property["PROPERTY TYPE"]
          seq = property["SEQ"]
          defaultValue = case propertyType
            when "string" then ""
            when "integer" then 0
            when "long" then 0
            when "float" then 0.0
            when "boolean" then false
          end

          if (!property["DEFAULT VALUE"].nil? && property["DEFAULT VALUE"] != "")
            defaultValue = property["DEFAULT VALUE"]
          end

          labelMeta = LabelMetum.new(label_id: labelId, name: propertyName, seq: seq, default_value: defaultValue, data_type: propertyType)
          labelMeta.save!
        end
      end
    end
  end

  def self.addIndices(labelId, indices, isModifyMode)
    #insert indices
    LabelIndex.transaction do
      indices = JSON.parse(indices)
      if (indices.size > 0 )
        indices.each do |index|
          indexName = index["INDEX NAME"]
          seq = index["SEQ"]
          metaSeqs= index["META SEQ"]
          existIndex = LabelIndex.where(label_id: labelId, name: indexName, seq: seq, meta_seqs: metaSeqs).take
          if existIndex.nil?
            labelIndex = LabelIndex.new(name: indexName, label_id: labelId, seq: seq, meta_seqs: metaSeqs, formulars: "none")
            labelIndex.save!
          end
        end
      else
        # 인덱스 없는 경우
        # _PK timestamp 0
        if (!isModifyMode)
          labelIndex = LabelIndex.new(name: "_PK", label_id: labelId, seq: 1, meta_seqs: 0, formulars: "none")
          labelIndex.save
        end
      end
    end
  end

  def addPropsAndIndices

    logger.error(label_params)
    labelId = params[:id]

    properties = label_params[:properties]
    indices = label_params[:indices]
    hbase_table_name = label_params[:hbase_table_name]

    logger.error(label_params)
    begin
      ActiveRecord::Base.transaction do
        @label.update(is_async: label_params[:is_async], hbase_table_name: hbase_table_name)
        LabelsController.addProps(labelId, properties)
        LabelsController.addIndices(labelId, indices, true)
      end
    rescue ActiveRecord::RecordNotFound => e
      render_result("fail", "adding props&indices is failed. : #{e}")
    rescue => e
      render_result("fail", "adding props&indices is failed. : #{e}")
    else
      render_result("success", "props&indices are added.")
    end

  end

  # DELETE /labels/1

  def destroy
    @label.destroy
    redirect_to labels_url, notice: 'Label was successfully destroyed.'
  end

  private

    def render_result(status, message)
      result = Hash["status" => status, "message" => message]
      render json: result.to_json
    end

    def self.service_column_find_or_insert(service_id, column_name, column_type, schema_version)
      sc = ServiceColumn.where(service_id: service_id, column_name: column_name ).take

app/helpers/labels_helper.rb
module LabelsHelper
end

app/views/labels/_editform.html.haml
= simple_form_for @label, method: :post, html: { id: "editing_label", name: "label-form", onsubmit: "return preSubmitForEdit()"} do |f|
  = f.error_notification
  %span#label-mode edit
  %span#label-id= @label.id
  %span.hidden-element#phase
    = Rails.application.config.phase
  - types = ["string", "integer", "long", "float", "boolean"]
  .form-wrap
    .form-inputs.form
      = f.input :label, label: "label name", required: true, :disabled => true
      %div#label-check-wraper
      = f.association :service, :label => "src service", :label_method => :service_name, :value_method => :id, input_html: { name: 'label[src_service_id]'}, required: true, :disabled => true
      = f.input :src_column_name, label: "src column name", required: true, :disabled => true
      = f.input :src_column_type, collection: types, label: "src column type", required: true, :disabled => true

      = f.association :service, :label => "tgt service", :label_method => :service_name, :value_method => :id, input_html: { name: 'label[tgt_service_id]'}, required: true, :disabled => true
      = f.input :tgt_column_name, label: "tgt column name", required: true, :disabled => true
      = f.input :tgt_column_type, collection: types, label: "tgt column type", required: true, required: true
      - if (!@selected_service_name.nil? && @selected_service_name != '')
        = f.input :service, :label => "service", :disabled => true, input_html: { value: @selected_service_name, name: 'service_id]'}, required: true
        = f.input :service, as: :hidden, input_html: { value: @selected_service_name, name: 'label[service_id]'}, :disabled => true
      - else
        = f.association :service, :label => "service", :label_method => :service_name, :value_method => :id, required: true, :disabled => true
      %hr
      %h4 properties & indices
      %table.table.table-hover#properties-table
        %thead
          %th PROPERTY NAME
          %th SEQ
          %th PROPERTY TYPE
          %th DEFAULT VALUE
          %th
        %tbody
          - if !@metas.nil? then
            - @metas.each do |meta|
              %tr
                %td
                  = meta.name
                %td
                  = meta.seq
                %td
                  = meta.data_type
                %td
                  = meta.default_value
                %td

      %input{type: "text", placeholder: "property name", class: "add-prop-name height-38", id: "property-name"}
      = select_tag :propertyType, options_for_select([''].concat(types), params[:propertyType]), {class: "add-prop-type select form-control", id: "property-type"}
      %input{type: "text", placeholder: "default value", class: "add-prop-default height-38", id: "property-default-value"}
      %span
        %button{ id: "btn-label-add-prop", class: "btn btn-sm btn-primary" } add property
      %table.table.table-hover#indices-table
        %thead
          %th INDEX NAME
          %th SEQ
          %th META SEQ
          %th
        %tbody
          - if !@indices.nil? then
            - @indices.each do |index|
              %tr
                %td
                  = index.name
                %td
                  = index.seq
                %td
                  = index.meta_seqs
                %td
      .row#index.hidden-element
        %input{type: "text", placeholder: "default value", class: "height-38", id: "index-name"}
        %span#index-select
          %select#index-select-box{ "multiple" => "multiple"}
        %span
          %button{ id: "btn-label-add-idx", class: "btn btn-sm btn-primary" } add index


      %hr
      %h4 label options
      %hr
      %div.form-group.string.optional.is-directed
        %label.string.optional.contol-label{ "for" => "is_directed"}
          %abbr{ "title" => "required"}
            *
          is directed
        %div.form-radio
          - directed = if @label.is_directed.nil? then 1 else @label.is_directed end
          - isTrue = if directed == 1 then "checked" else nil end
          - isFalse = if directed == 0 then "checked" else nil end
          %input{type:"radio", value: 1, "checked" => isTrue, name: "label[is_directed]", :disabled => true}
            true
          %span.blank-span
          %input{type:"radio", value: 0, "checked" => isFalse, name: "label[is_directed]", :disabled => true}
            false
      %div.form-group.string.optional.consistency-level
        %label.string.optional.contol-label{ "for" => "consistency_level"}
          %abbr{ "title" => "required"}
            *
          consistency level
        %div.form-radio
          - consistencyLevel = if @label.consistency_level.nil? then "strong" else @label.consistency_level end
          - isStrong = if consistencyLevel == "strong" then "checked" else nil end
          - isWeak = if consistencyLevel == "weak" then "checked" else nil end
          %input{type:"radio", value: "strong", "checked" => isStrong, name: "label[consistency_level]", :disabled => true}
            strong
          %span.blank-span
          %input{type:"radio", value: "weak", "checked" => isWeak, name: "label[consistency_level]", :disabled => true}
            weak
      = f.input :hbase_table_name, id: "label-form-htable-name", :label => "hbase table name", input_html: { value: @hbase_table_name }
      = f.input :hbase_table_ttl, :label => "hbase table ttl", :disabled => true
      = f.input :schema_version,  :label => "schema version", :disabled => true, input_html: { value: @label.schema_version, name: 'label[schema_version]'}, required: true
      = f.input :schema_version, as: :hidden, input_html: { value: @label.schema_version, name: 'label[schema_version]'}
      %div.form-group.string.optional.is-async
        %label.string.optional.contol-label{ "for" => "is_async"}
          %abbr{ "title" => "required"}
            *
          is async
        %div.form-radio
          - async = if @label.is_async.nil? then 0 else @label.is_async end
          - isF = if async == 0 then "checked" else nil end
          - isT = if async == 1 then "checked" else nil end
          %input{type:"radio", value: 0, "checked" => isF, name: "label[is_async]"}
            false
          %span.blank-span
          %input{type:"radio", value: 1, "checked" => isT, name: "label[is_async]"}
            true
      %div.form-group.string.optional.compressionAlgorithm
        %label.string.optional.contol-label{ "for" => "compressionAlgorithm"}
          %abbr{ "title" => "required"}
            *
          compression algorithm
        %div.form-radio
          - compression = if @label.compressionAlgorithm.nil? then "lz4" else @label.compressionAlgorithm end
          - isLZ4 = if compression == "lz4" then "checked" else nil end
          - isGZ = if compression == "gz" then "checked" else nil end
          %input{type:"radio", value: 'lz4', "checked" => isLZ4, name: "label[compressionAlgorithm]", :disabled => true}
            lz4
          %span.blank-span
          %input{type:"radio", value: 'gz', "checked" => isGZ, name: "label[compressionAlgorithm]", :disabled => true}
            gz

    .form-actions
      = f.button :submit, :class => 'btn btn-primary'

app/views/labels/_form.html.haml
= simple_form_for @label, html: { name: "label-form", onsubmit: "return preSubmit()"} do |f|
  = f.error_notification
  %span.hidden-element#phase
    = Rails.application.config.phase
  - columnTypes = ["string", "integer", "long"]
  - types = ["string", "integer", "long", "float", "boolean"]
  .form-wrap
    .form-inputs.form
      = f.input :label, label: "label name", required: true
      %div#label-check-wraper
        %span#notice-label-check
        %button{ id: "btn-label-check-duplicate", class: "btn btn-sm btn-warning" } check duplicate
      = f.association :service, :label => "src service", :label_method => :service_name, :value_method => :id, input_html: { name: 'label[src_service_id]'}, required: true
      = f.input :src_column_name, label: "src column name", required: true
      = f.input :src_column_type, collection: columnTypes, label: "src column type", required: true

      = f.association :service, :label => "tgt service", :label_method => :service_name, :value_method => :id, input_html: { name: 'label[tgt_service_id]'}, required: true
      = f.input :tgt_column_name, label: "tgt column name", required: true
      = f.input :tgt_column_type, collection: columnTypes, label: "tgt column type", required: true, required: true
      - if (!@selected_service_name.nil? && @selected_service_name != '')
        = f.input :service, :label => "service", :disabled => true, input_html: { value: @selected_service_name, name: 'service_id]'}, required: true
        = f.input :service, as: :hidden, input_html: { value: @selected_service_name, name: 'label[service_id]'}
      - else
        = f.association :service, :label => "service", :label_method => :service_name, :value_method => :id, required: true
      %hr
      %h4 properties & indices
      %table.table.table-hover#properties-table
        %thead
          %th PROPERTY NAME
          %th SEQ
          %th PROPERTY TYPE
          %th DEFAULT VALUE
          %th 
        %tbody
          - if !@metas.nil? then 
            - @metas.each do |meta|
              %tr
                %td
                  = meta.name
                %td
                  = meta.seq
                %td
                  = meta.data_type
                %td
                  = meta.default_value
                %td

      %input{type: "text", placeholder: "property name", class: "add-prop-name height-38", id: "property-name"}
      = select_tag :propertyType, options_for_select([''].concat(types), params[:propertyType]), {class: "add-prop-type select form-control", id: "property-type"}
      %input{type: "text", placeholder: "default value", class: "add-prop-default height-38", id: "property-default-value"}
      %span
        %button{ id: "btn-label-add-prop", class: "btn btn-sm btn-primary" } add property
      %table.table.table-hover#indices-table
        %thead
          %th INDEX NAME
          %th SEQ
          %th META SEQ
          %th 
        %tbody
          - if !@indices.nil? then 
            - @indices.each do |index|
              %tr
                %td
                  = index.name
                %td
                  = index.seq
                %td
                  = index.meta_seqs
                %td
      .row#index.hidden-element
        %input{type: "text", placeholder: "default value", class: "height-38", id: "index-name"}
        %span#index-select
          %select#index-select-box{ "multiple" => "multiple"}
        %span
          %button{ id: "btn-label-add-idx", class: "btn btn-sm btn-primary" } add index


      %hr
      %h4 label options
      %hr
      %div.form-group.string.optional.is-directed
        %label.string.optional.contol-label{ "for" => "is_directed"}
          %abbr{ "title" => "required"}
            *
          is directed
        %div.form-radio
          - directed = if @label.is_directed.nil? then 1 else @label.is_directed end
          - isTrue = if directed == 1 then "checked" else nil end
          - isFalse = if directed == 0 then "checked" else nil end
          %input{type:"radio", value: 1, "checked" => isTrue, name: "label[is_directed]"}
            true
          %span.blank-span
          %input{type:"radio", value: 0, "checked" => isFalse, name: "label[is_directed]"}
            false
      %div.form-group.string.optional.consistency-level
        %label.string.optional.contol-label{ "for" => "consistency_level"}
          %abbr{ "title" => "required"}
            *
          consistency level
        %div.form-radio
          - consistencyLevel = if @label.consistency_level.nil? then "strong" else @label.consistency_level end
          - isStrong = if consistencyLevel == "strong" then "checked" else nil end
          - isWeak = if consistencyLevel == "weak" then "checked" else nil end
          %input{type:"radio", value: "strong", "checked" => isStrong, name: "label[consistency_level]"}
            strong
          %span.blank-span
          %input{type:"radio", value: "weak", "checked" => isWeak, name: "label[consistency_level]"}
            weak
      = f.input :hbase_table_name, id: "label-form-htable-name", :label => "hbase table name", input_html: { value: @service_htable_name }
      = f.input :hbase_table_ttl, :label => "hbase table ttl"
      = f.input :schema_version,  :label => "schema version", :disabled => true, input_html: { value: "v3", name: 'label[schema_version]'}, required: true
      = f.input :schema_version, as: :hidden, input_html: { value: "v3", name: 'label[schema_version]'}
      %div.form-group.string.optional.is-async
        %label.string.optional.contol-label{ "for" => "is_async"}
          %abbr{ "title" => "required"}
            *
          is async
        %div.form-radio
          - async = if @label.is_async.nil? then 0 else @label.is_async end
          - isF = if async == 0 then "checked" else nil end
          - isT = if async == 1 then "checked" else nil end
          %input{type:"radio", value: 0, "checked" => isF, name: "label[is_async]"}
            false
          %span.blank-span
          %input{type:"radio", value: 1, "checked" => isT, name: "label[is_async]"}
            true
      %div.form-group.string.optional.compressionAlgorithm
        %label.string.optional.contol-label{ "for" => "compressionAlgorithm"}
          %abbr{ "title" => "required"}
            *
          compression algorithm
        %div.form-radio
          - compression = if @label.compressionAlgorithm.nil? then "lz4" else @label.compressionAlgorithm end
          - isLZ4 = if compression == "lz4" then "checked" else nil end
          - isGZ = if compression == "gz" then "checked" else nil end
          %input{type:"radio", value: 'lz4', "checked" => isLZ4, name: "label[compressionAlgorithm]"}
            lz4
          %span.blank-span
          %input{type:"radio", value: 'gz', "checked" => isGZ, name: "label[compressionAlgorithm]"}
            gz

    .form-actions
      = f.button :submit, :class => 'btn btn-primary'

app/views/labels/edit.html.haml
%h3 EDITING LABEL
#s2admin-form-layout
  = render 'editform'
  = link_to 'Show', @label
  |
  \#{link_to 'Back', labels_path}

app/views/labels/index.html.haml
%p#notice= notice
#s2admin-contents-layout
  .row
    .col-md-12.btn-create
      = button_to 'CREATE LABEL', new_label_path, class: "btn btn-primary", method: :get
  .row
    %div{class: "form-group pull-right"}
      %input{type:"text", class:"search form-control", placeholder:"search"}
    %span{class: "counter pull-right"}
    %table.table.table-hover.results
      %thead
        %tr
          %th LABEL
          %th SRC SERVICE
          %th SRC COLUMN NAME
          %th SRC COLUMN TYPE
          %th TGT SERVICE
          %th TGT COLUMN NAME
          %th TGT COLUMN TYPE
          %th IS DIRECTED
          %th SERVICE NAME
          %th SERVICE
          %th CONSISTENCY LEVEL
          %th HBASE TABLE NAME
          %th HBASE TABLE TTL
          %th SCHEMA VERSION
          %th IS ASYNC
          %th COMPRESSIOIN ALGORITHM
      %tbody
        - @labels.each do |label|
          %tr{onClick: "location.href='/labels/#{label.id}'", style: "cursor:pointer;"}
            %td= label.label
            %td= label.src_service_id
            %td= label.src_column_name
            %td= label.src_column_type
            %td= label.tgt_service_id
            %td= label.tgt_column_name
            %td= label.tgt_column_type
            %td= label.is_directed
            %td= label.service_name
            %td= label.service_id
            %td= label.consistency_level
            %td= label.hbase_table_name
            %td= label.hbase_table_ttl
            %td= label.schema_version
            %td= label.is_async
            %td= label.compressionAlgorithm
  .row
    .col-md-12.btn-create
      = button_to 'CREATE LABEL', new_label_path, class: "btn btn-primary", method: :get

app/views/labels/new.html.haml
%h3 CREATE LABEL
#s2admin-form-layout
  = render 'form'
  = link_to 'Back', labels_path

app/views/labels/show.html.haml
%p#notice= notice
%div#s2admin-contents-layout
  %div#label-detail-wrap
    .row.label-detail-title
      %strong label:
      = @label.label
    %hr
    .row.label-each-column
      %strong src service:
      = @label.src_service_id
    .row.label-each-column
      %strong src column name:
      = @label.src_column_name
    .row.label-each-column
      %strong src column type:
      = @label.src_column_type
    %hr
    .row.label-each-column
      %strong tgt service:
      = @label.tgt_service_id
    .row.label-each-column
      %strong tgt column name:
      = @label.tgt_column_name
    .row.label-each-column
      %strong tgt column type:
      = @label.tgt_column_type
    %hr
    .row.label-each-column
      %strong is directed:
      = @label.is_directed
    .row.label-each-column
      %strong service name:
      = @label.service_name
    .row.label-each-column
      %strong service:
      = @label.service_id
    .row.label-each-column
      %strong consistency level:
      = @label.consistency_level
    .row.label-each-column
      %strong hbase table name:
      = @label.hbase_table_name
    .row.label-each-column
      %strong hbase table ttl:
      = @label.hbase_table_ttl
    .row.label-each-column
      %strong schema version:
      = @label.schema_version
    .row.label-each-column
      %strong is async:
      = @label.is_async
    .row.label-each-column
      %strong compressionalgorithm:
      = @label.compressionAlgorithm
    %hr
    .row.label-each-column
      %pre.contents-value.json-body= JSON.pretty_generate(LabelMetum.where(label_id: @label.id).as_json)
    %hr
    .row
      = button_to 'EDIT', edit_label_path(@label), class: "btn btn-primary pull-right label-below-btn", method: :get
      = button_to 'BACK', service_path(@label.service_id), class: "btn btn-warning pull-right label-below-btn", method: :get