config/routes.rb
Rails.application.routes.draw do

  resources :counters
  get 'talk_tabs', to: 'talk_tabs#index'
  # get 'admin/index'

  # get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end


  root to: 'experiments#index'

  resources :column_meta
  resources :label_meta
  resources :services  do
    member do
      put 'access_token', to: 'services#updateAccessToken'
    end
  end

  resources :labels, except: [:update] do
    member do
      post 'add_props_and_indices', to: 'labels#addPropsAndIndices'
    end
  end

  resources :buckets, only: [:new, :create, :edit, :show, :update, :destroy] do
    member do
      put 'copy_bucket', to: 'buckets#copyBucket'
    end
  end
  resources :services
  
  # resources :users, only: [:new, :create, :edit, :update, :destroy]
  resources :users do
    member do
      get :info
    end
  end
  resources :authorities
  resources :s2ml_apps
	resources :s2loader_jobs
  resources :s2admin_demos do
    member do
      get :demo
      get :default_id
    end
  end
  resources :experiments do
    member do
      get :detail
      post :modular
    end
  end

  post 'buckets/validate/request_body', to: 'buckets#validateRequestBody'

  get 'queries/visualize'

  post 'queries/partial_graph', to: 'queries#partialGraph'

  post 'queries/call_graph', to: 'queries#callGraph'

  get 'labels/check/:label_name', to: 'labels#check'

  get 'buckets/check/:impression_id', to: 'buckets#check'

  get 's2graph', to: 'services#index'

  get 's2counter', to: 'counters#index'

  get 'users', to: 'users#index'

  get 'access', to: 'authorities#index'

  get 's2ab', to: 'experiments#index'

  post 's2ab/:access_token/ratio-update-all', to: 'experiments#ratioUpdateAll'

  get 's2ab/:access_token/list(/:experiment_name)', to: 'experiments#list'

  get 's2ml', to: 's2ml_apps#index'

  get 's2ml_apps/:id/disable', to: 's2loader_jobs#disable'

  get 's2ml_apps/:id/enable', to: 's2loader_jobs#enable'

  get 's2loader', to: 's2loader_jobs#index'

  get 's2loader_jobs/:id/test', to: 's2loader_jobs#test'

  get 's2loader_jobs/:id/disable', to: 's2loader_jobs#disable'

  get 's2loader_jobs/:id/enable', to: 's2loader_jobs#enable'

  get 'demos', to: 's2admin_demos#index'

  get 'demos/:id/demo', to: 's2admin_demos#demo'

  get 'demos/update_descriptions', to: 's2admin_demos#update_descriptions'

  get 'demos/s2graph', to: 's2admin_demos#index'

  get 'demos/s2counter', to: 's2admin_demos#demo_counter.html.haml'

  get 'demos/talk-channel', to: 'talk_tabs#index'

  get 'links', to: 'links#list'

  get 'servers', to: 'servers#index'

  put 'servers/:server/:status', to: 'servers#toggle_health'

  get 'servers/load', to: 'servers#high_loads'

  get 'servers/latency', to: 'servers#high_latencies'
end

app/models/experiment.rb
class Experiment < ActiveRecord::Base
  belongs_to :service
  has_many :buckets
  # TODO: move to ENV per phase
  def s2_url
    APP_CONFIG['s2graph_url']+'/graphs/getEdges'
  end

  def self.time_iterate(start_time, end_time, step, &block)
    arr = []
    begin
      yield start_time if block_given?
      arr << start_time
    end while (start_time += step) <= end_time
    arr
  end

  def make_chart(nom, denom, time_unit, _from, _to)
    begin
      is_single_action = nom == denom
      time_step =
        if time_unit.to_sym == :H
          60*60*1000
        elsif time_unit.to_sym == :d
          60*60*1000*24
        end

      from, to = (_from / time_step * time_step), (_to / time_step * time_step)

      # FIXME
      to -= 9.hours * 1000
      from -= 9.hours * 1000

      query = build_query(time_unit, from, to, [nom, denom])
      #logger.info(query.to_json)
      res = RestClient.post s2_url, query.to_json, :content_type => :json, :accept => :json
      parsed = (JSON.parse(res) rescue {}).with_indifferent_access
      results = parsed[:results]
      #logger.info results
      xAxis = Experiment.time_iterate(from, to, time_step)
      series_ls = results.map do |grouped|
        bucket_name = grouped[:groupBy][:from]

        time_action_map = {}
        grouped[:agg].each do |edge|
          props = edge[:props]
          time_value = props[:time_value]
          count = props[:_count] || props[:count] # FIXME: '_count' is correct
          action = edge[:to].split(".").last
          time_action_map["#{time_value}_#{action}"] = count.to_f
        end

        sum_top = 0
        sum_bottom = 0
        series = xAxis.map { |tm|
          _nom, _denom = "#{tm}_#{nom}", "#{tm}_#{denom}"
          bottom = is_single_action ? 1 : time_action_map.fetch(_denom, 1)
          top = time_action_map.fetch(_nom, 0)
          ctr = (top / bottom).round(5)

          sum_top += top
          sum_bottom += bottom
          ["#{nom}: #{top}<br />#{denom}: #{bottom}", ctr, {conversions: top, visitors: bottom, conversion_rate: ctr}]
        }
        g_ctr = sum_bottom == 0 ? sum_top.round(5) : (sum_top/sum_bottom).round(5)
        series.push(["overall result (#{sum_top}/#{sum_bottom})", g_ctr, {conversions: sum_top, visitors: sum_bottom, conversion_rate: g_ctr}])
        { name: bucket_name, data: series }
      end

      series_ls = series_ls.map do |test_a|
        explain_list = series_ls.map do |test_b|
          explain = []
          test_a[:data].zip(test_b[:data]).each do |data_a, data_b|
            support_sent = ''
            if test_a[:name] != test_b[:name]
              a = data_a[2]
              b = data_b[2]
              if a[:visitors] > 0 && b[:visitors] > 0 && (a[:conversion_rate] <= 1 && a[:conversion_rate] > 0 && b[:conversion_rate] <= 1 && b[:conversion_rate] > 0)
                x = Math.sqrt((a[:conversion_rate] * (1 - a[:conversion_rate])) / a[:visitors])
                y = Math.sqrt((b[:conversion_rate] * (1 - b[:conversion_rate])) / b[:visitors])
                s = (a[:conversion_rate] - b[:conversion_rate]) / Math.sqrt(x * x + y * y)
                if a[:conversion_rate] > b[:conversion_rate]
                  certainty = ExperimentsHelper.normdist(s, 0, 1, true)
                else
                  certainty = 1 - ExperimentsHelper.normdist(s, 0, 1, true)
                end
                if a[:conversion_rate] >= b[:conversion_rate]
                  if b[:conversion_rate] > 0
                    improvement = (a[:conversion_rate] - b[:conversion_rate]) / b[:conversion_rate]
                  else
                    improvement = a[:conversion_rate]
                  end
                  support_sent = "<br />certainty: #{(certainty * 100).round(2)}% improvement: #{(improvement * 100).round(2)}% over #{test_b[:name]}"
                end
              end
            end
            explain.push(support_sent)
          end
          explain
        end
        { name: test_a[:name], data: test_a[:data].each_with_index.map { |x, i| [x[0] + explain_list.map{ |e| e[i] }.join(''), x[1]] } }
      end

      ##logger.info series_ls

      sub_title = is_single_action ? nom.to_s.camelize : "#{nom.to_s.camelize} / #{denom.to_s.camelize}"
      ret = {
        chart: { zoomType: 'x' },
        title: { text: service.service_name },
        tooltip: { crosshairs: true, shared: false },
        subtitle: { text: sub_title },
        xAxis: { categories: xAxis.map{|tm| Time.at(tm/1000).strftime("%Y-%m-%d %H:%M") } << 'Overall' },
        yAxis: { title: { text: :ctr } },
        plotOptions: { line: { dataLabels: { enabled: true }, enableMouseTracking: true } },
        series: series_ls.sort_by { |h| h[:name] }
      }
      ret
    rescue => e
      nil
    end
  end

  def build_query(time_unit, from, to, action_types)
    ids = buckets.map(&:impression_id)
    sources = [ { serviceName: :s2ab, columnName: :bucket_id, ids: ids } ]

    first_step = action_types.map do |action|
      {
        direction: :out,
        duplicate: :raw,
        label: :s2ab_feedback_counts,
        limit: -1,
        offset: 0,
        interval: {
          from: {
            _to: "action_type.#{action}",
            time_unit: time_unit,
            time_value: from
          },
          to: {
            _to: "action_type.#{action}",
            time_unit: time_unit,
            time_value: to
          }
        }
      }
    end
    step_hash = { step: first_step }
    {
      groupBy: %i[from],
      srcVertices: sources,
      steps: [step_hash]
    }
  end

  def action_types
    # FIXME: just mock, move to database
    %i[click buy purchase download invite register impression]
  end
end

app/controllers/experiments_controller.rb
# coding: utf-8
class ExperimentsController < ApplicationController
  include Util
  before_action :set_experiment, only: [:show, :edit, :update, :destroy, :ctr, :detail]
  before_action :set_active
  skip_before_filter :authorize, only: [:ratioUpdateAll]
  skip_before_filter :verify_authenticity_token, only: [:ratioUpdateAll]

  # GET /experiments/
  def index
    # @experiments = Experiment.includes(:buckets)

    # exps = Experiment.includes(:service => [:authorities => [{ :user => session[:user_id]}]])
    user = User.find(session[:user_id])
    @exps = nil
    if user.authority == 'master' then
      @exps = Experiment.all.order(:service_name)
    else
      authorities = Authority.where(user_id: session[:user_id]).select("service_id")
      @exps = Experiment.where(service_id: authorities).order(:service_name)
    end

    @experiments_hash = {}
    for exp in @exps
      if @experiments_hash[exp.service_name].nil?
        @experiments_hash[exp.service_name] = []
      end
      @experiments_hash[exp.service_name].push(exp)
    end

  end

  # GET /experiments/1
  def show
  end

  #POST /experiments/1/modular
  def modular

    paramsToUpdate = params.except(:controller, :action, :id)
    keys = paramsToUpdate.keys
    values = paramsToUpdate.values.map do |value|
      Hash["modular" => value]
    end

    if Bucket.update(keys, values)
      result = Hash["status" => "success"]
      render json: result.to_json
    else
      result = Hash["status" => "fail"]
      render json: result.to_json
    end
  end

  #GET s2ab/:access_token/list/:experiment_name
  def list
    access_token = params[:access_token]
    experiment_name = params[:experiment_name]
    if experiment_name.nil?
      serviceId = Service.where(access_token: access_token).take.id
      experiments = Experiment.where(service_id: serviceId)
      exps = experiments.map do | experiment |
        experimentId = experiment.id
        experiment = experiment.as_json.merge({buckets: Bucket.where(experiment_id: experimentId)})
      end
      render json: exps.to_json
    else
      serviceId = Service.where(access_token: access_token).take.id
      experiments = Experiment.where(service_id: serviceId, name: experiment_name)
      exps = experiments.map do | experiment |
        experimentId = experiment.id
        experiment = experiment.as_json.merge({buckets: Bucket.where(experiment_id: experimentId)})
      end
      render json: exps.to_json
    end
    
  end

  
  #POST s2ab/:access_token/ratio-update-all
  def ratioUpdateAll
    begin
      access_token = params[:access_token]
      service = Service.where(access_token: access_token).take
      if service.nil?
        render_result("fail", "Invalid access_token.")
      end
      experiment = Experiment.where(service_id: service.id, name: params[:test_name]).take

      if experiment.nil?
        render_result("fail", "There is no experiment.")
      end

      buckets = Bucket.where(experiment_id: experiment.id)
      if (buckets.nil? || buckets.size == 0)
        render_result("fail", "There is no bucket.")
      end

      ratios = params[:ratios]

      keys ||= Array.new
      values ||= Array.new
      ratios.each do |ratio|
        bucket = buckets.where(impression_id: ratio[:impression_id]).take
        keys.push(bucket[:id])
        values.push(Hash["modular" => ratio[:ratio]])
      end

      if (ratios.size == keys.size && keys.size == values.size)
        if Bucket.update(keys, values)
          render_result("success", "Ratios is updated.")
        else
          render_result("fail", "DB error.")
        end
      else
        render_result("fail", "Invalid json format.")
      end
    rescue
      render_result("fail", "Invalid json format.")
    end
  end


  # GET /experiments/1/detail
  def detail
    @experiments = Experiment.includes(:buckets).where("id = ?", @experiment.id)

    experiment = Experiment.find(@experiment.id)

    @access_token = Service.find(experiment.service_id).access_token
    # logger.error("===================")
    # logger.error( @experiment.buckets.joins("LEFT JOIN users ON (users.id = 'updated_by')").select("buckets.*, users.email as update_by_email").to_json)

    # logger.error("===================")
    @service, @buckets = @experiment.service, @experiment.buckets.order(:impression_id)
    action_types = @experiment.action_types
    @action_types_for_view = action_types.map { |a| [a, a] }

    # from params[:xx]
    @from, @to = params.values_at(:from_time, :to_time)
    @time_units = [:H, :d]
    @time_unit = params.fetch(:time_unit, :d).to_sym

    if @time_unit == :H
      from = (@from ? (DateTime.parse(@from).beginning_of_day).to_i : (Time.now.beginning_of_day - 1.days).to_i) * 1000
      to = (@to ? (DateTime.parse(@to).end_of_day).to_i : (Time.now.end_of_day).to_i) * 1000
    else
       from = (@from ? (DateTime.parse(@from)).to_i : (Time.now - 14.days).to_i) * 1000
      to = (@to ? (DateTime.parse(@to)).to_i : (Time.now).to_i) * 1000
    end

    @from = Time.at(from/1000).strftime("%Y-%m-%d") if @from.nil?
    @to = Time.at(to/1000).strftime("%Y-%m-%d") if @to.nil?

    @nom = params.fetch(:nom, action_types.first)
    @denom = params.fetch(:denom, action_types.last)

    @chart_data = @experiment.make_chart(@nom, @denom, @time_unit, from, to)

    respond_to do |format|
      format.html
      format.json { render json: @chart_data }
    end

  end

  # GET /experiments/new
  def new
    @experiment = Experiment.new
  end

  # GET /experiments/1/edit
  def edit
  end

  # POST /experiments
  def create
    @experiment = Experiment.new(experiment_params.merge({created_by: getUserName(session[:user_id])}))

    if @experiment.save
      redirect_to s2ab_path, notice: 'Test was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /experiments/1
  def update
    if @experiment.update(experiment_params.merge({updated_by: getUserName(session[:user_id])}))
      redirect_to s2ab_path, notice: 'Test was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /experiments/1
  def destroy
    @experiment.destroy
    redirect_to s2ab_path, notice: 'Test was successfully destroyed.'
  end

  private
  # Use callbacks to share common setup or constraints between actions.
    def render_result(status, msg)
      result = Hash["status" => status, "msg" => msg]
      render json: result.to_json
    end

    def set_experiment
      @experiment = Experiment.find(params[:id])
      has_authority
    end

    def has_authority
      user = User.find(session[:user_id])
      if user.authority != "master" then
        authorities = Authority.where(user_id: session[:user_id], service_id: @experiment.service_id)
        if authorities.size <= 0
          raise "error"
        end
      end
    end

    # Only allow a trusted parameter "white list" through.
    def experiment_params
      @service = Service.find(params[:experiment][:service_id])
      @service_name = @service.service_name
      params[:experiment][:service_name] = @service_name
      params.require(:experiment).permit(:service_id, :service_name, :name, :description, :experiment_type, :total_modular)
    end

    def set_active
      @active = "s2ab"
    end
end

app/helpers/experiments_helper.rb
module ExperimentsHelper

  # https://gist.github.com/gareth/1349891
  def self.normdist(x, mean, std, cumulative)
    if cumulative
      phi_around x, mean, std
    else
      tmp = 1/((Math.sqrt(2*Math::PI)*std))
      tmp * Math.exp(-0.5 * ((x-mean)/std ** 2))
    end
  end

  # fractional error less than 1.2 * 10 ^ -7.
  def self.erf(z)
    t = 1.0 / (1.0 + 0.5 * z.abs);

    # use Horner's method
    ans = 1 - t * Math.exp(-z*z - 1.26551223 + t * (1.00002368 + t * (0.37409196 +
        t * (0.09678418 + t * (-0.18628806 + t * (0.27886807 + t * (-1.13520398 +
            t * (1.48851587 + t * (-0.82215223 + t * (0.17087277))))))))))

    z >= 0 ? ans : -ans
  end

  # cumulative normal distribution
  def self.phi(z)
    return 0.5 * (1.0 + erf(z / (Math.sqrt(2.0))));
  end

  # cumulative normal distribution with mean mu and std deviation sigma
  def self.phi_around(z, mu, sigma)
    return phi((z - mu) / sigma);
  end

end

app/views/experiments/detail.html.haml
%div{:class => "row"}
  .col-md-12
    .row
      .col-md-12#experiment-title
        %span
          = @experiment.name
        %span{id: "experiment-id"}
          = @experiment.id
        %span{id: "service-id"}
          = @experiment.service_id
        %span{id: "experiment-modify", class: "glyphicon glyphicon-pencil", "aria-hidden" => "true"}
        %span{id: "experiment-delete", class: "glyphicon glyphicon-trash", "aria-hidden" => "true"}
    %hr
    .row.experiment-div
      .row
        .col-md-12.contents-div service name : #{@service.service_name}
      .row
        .col-md-12.contents-div type(U/T) : #{@experiment.experiment_type}
      .row
        .col-md-12.contents-div{id: "total-modular"} total modular : #{@experiment.total_modular}
      .row
        .col-md-12.contents-div description : #{@experiment.description}
      .row
        .col-md-12.contents-div
          - if @access_token.nil?
            %div{class: "access-token-warning", role: "alert"} access_token is missing.
            %button{type: "button", class: "btn btn-primary btn-sm", id: "gen-access-token", "data-toggle" => "modal", "data-target" => "#gen-access-token-modal"} generate

          - else
            access token :
            = @access_token
          %div{id: "gen-access-token-modal", class: "modal fade", "role" => "dialog"}
            %div{class: "modal-dialog modal-sm modal-access-token"}
              %div{class: "modal-content"}
                %div{class: "modal-header"}
                  %h6{class: "modal-title"}Generate ACCESS_TOKEN
                %div{class: "modal-body"}
                  %div{id: "uuid"}
                %div{class: "modal-footer"}
                  %button{type: "button", class: "btn btn-primary btn-sm", id: "btn-save-access-token"}Save
                  %button{type: "button", class: "btn btn-default btn-sm", "data-dismiss" => "modal"}Close
      .row
        .col-md-12.contents-div
          %button{type: "button", class: "btn btn-primary btn-sm", "data-toggle" => "modal", "data-target" => "#bucket-modify", id: "btn-modify-ratio"} EDIT BUCKETS RATIO
    %hr

    -#- sorted_buckets = @buckets.sort_by { |b| b.impression_id }

    %div{id: "bucket-modify", class: "", "role" => "dialog"}
      %div{class: "modal-dialog modal-lg"}
        %div{class: "modal-content"}
          %div{class: "modal-header"}
            %h4{class: "modal-title"}Editing Buckets Ratio
            %div{class: "modal-body"}
              %div{class: "center"}
                %br/
                %br/
                %div{id: "slider"}
                  %table{id: "range", width: "100%", cellspacing: "0", cellpadding: "0"}
                    %tr
                      - @buckets.each_with_index do |bucket, index|
                        %td{class: "bucket bucket-#{index%5}", width: "#{bucket.ratio}%"}
                          = bucket.impression_id

                %p{id: "text"}= "Ranges: #{@buckets.collect{|x| x.ratio}.join('%, ')}"

              .row
              - i = 0
              - for bucket in @buckets
                .row.bucket-modify-row
                  %label{class: "string control-label display-inline-block"}
                    = bucket.impression_id
                  %input{class: "modular-value string form-control display-inline-block", type: "text", value: "#{bucket.modular}", name: "#{bucket.id}", id: "bucket-#{i}"}
                - i += 1
            %div{class: "modal-footer"}
              %button{type: "button", class: "btn btn-primary", id: "buckets-save"} Save
              %button{type: "button", class: "btn btn-default", "data-dismiss" => "modal"}Close




    .row
      %div{class: "form-group pull-right"}
        %input{type:"text", class:"search form-control", placeholder:"search"}
      %span{class: "counter pull-right"}
      %table.table.table-hover.results
        %thead
          %th #
          %th EXPERIMENT ID
          %th IMPRESSION ID
          %th DESCRIPTION
          %th MODULAR
          %th HTTP VERB
          %th IS GRAPH
          %th TIMEOUT
          %th API PATH
          %th UPDATED BY
          %th UPDATED AT
          %th
          %th
          %th
          %th
        %tbody
          - for bucket in @buckets
            %tr
              %td
                = bucket.id
              %td
                = bucket.experiment_id
              %td
                = bucket.impression_id
              %td
                = bucket.description
              %td
                = bucket.modular
              %td
                = bucket.http_verb
              %td
                = bucket.is_graph_query
              %td
                = bucket.timeout
              %td
                = bucket.api_path
              %td
                = bucket.updated_by.presence || bucket.created_by.presence || ''
              %td
                = bucket.updated_at.present? ? bucket.updated_at.strftime("%Y-%m-%d %H:%M") : bucket.created_at.present? ? bucket.created_at.strftime("%Y-%m-%d %H:%M") : ''
              %td
                -if !bucket.variables.nil? && bucket.variables != ""
                  = link_to "graph", "", class: "btn btn-info btn-sm", :onclick => "showGraph('#{bucket.impression_id}', '#{@experiment.id}-#{bucket.id}', '#{bucket.api_path}'); return false"
                    
              %td
                %button{type: "button", class: "btn btn-warning btn-sm", "data-toggle" => "modal", "data-target" => "##{@experiment.id}-#{bucket.id}"} details
              %td
                %a{href: "javascript:copyBucket(#{@experiment.id}, #{bucket.id})", class: "btn btn-success btn-sm" } copy bucket
              %td
                \#{link_to '', edit_bucket_path(bucket), class: "glyphicon glyphicon-pencil bucket-modify"}
              %td
                \#{link_to '', bucket, method: :delete, data: { confirm: 'Are you sure?' }, class: "glyphicon glyphicon-trash bucket-delete"}
    .row
      .col-md-12#btn-create-bucket
        = button_to 'add bucket', new_bucket_path, params: {:id => @experiment, :name => @experiment.name}, :class => "btn btn-primary", :method => :get
%hr
  %form.action_types#chart-form
    %div.chart-param
      %span from
      %input.datepicker{ type: :text, name: :from_time, value: @from, "data-provide" => "datepicker" }
      %span to
      %input.datepicker{ type: :text, name: :to_time, value: @to, "data-provide" => "datepicker" }
      %span dimension
      %select.form-control{ name: :time_unit }
        = options_for_select(@time_units.map{|a| [a, a]}, @time_unit)

      %span numerator
      %select.form-control{ name: :nom }
        = options_for_select(@action_types_for_view, @nom)
      %span /
      %span denominator
      %select.form-control{ name: :denom }
        = options_for_select(@action_types_for_view, @denom)
      %span#exp_id #{@experiment.id}
      %span#get_chart.btn-submit
      %button{type: :submit, class: "btn btn-primary btn-sm"} GET CHART

  - rowSize = 0
  - colSize = 0
  - if !@chart_data.nil?
    - rowSize = @chart_data[:xAxis][:categories].size
    - colSize = @chart_data[:series].size

  - if colSize > 0
    %hr
      #ctr-chart

      %span#toggle_series
      %button{type: :button, class: "btn btn-primary btn-xs", id:"toggle-series"} TOGGLE ALL

    %hr
    .row
      %table.table.table-striped
        %thead
          %th
            date
          - for col in 0 .. colSize-1
            %th
              = @chart_data[:series][col][:name]
        %tbody
          - for row in 0 .. rowSize-1
            %tr
              %td
                = @chart_data[:xAxis][:categories][row]
              - for col in 0 .. colSize-1
                %td
                  = @chart_data[:series][col][:data][row][1]
  - else
    .row
      %div#no-data
        There is no data.

  - for bucket in @buckets
    %div{id: "#{@experiment.id}-#{bucket.id}", class: "modal fade", "role" => "dialog"}
      %div{class: "modal-dialog modal-lg"}
        %div{class: "modal-content"}
          %div{class: "modal-header"}
            %h4{class: "modal-title"}Request Body
          %div{class: "modal-body"}
            %pre.contents-value= "/graphs/experiment/#{@access_token}/#{@experiment.name}/[ID]"
            %pre.contents-value.json-body= bucket.request_body
            %pre.hidden= bucket.request_body
          %div{class: "modal-footer"}
            %button{type: "button", class: "btn btn-default", "data-dismiss" => "modal"}Close


%script{ :type => 'text/javascript' }
  vm.chartData = #{@chart_data.to_json.html_safe};
  var variablesObject = {};
  - for bucket in @buckets
    - if !bucket.variables.nil?
      variablesObject["#{bucket.impression_id}"] = #{bucket.variables.html_safe};

app/views/experiments/edit.html.haml
%h3 EDITING TEST
#s2admin-form-layout
  = render 'form'
  = link_to 'Show', @experiment
  |
  \#{link_to 'Back', detail_experiment_path}

app/views/experiments/index.html.haml
%p#notice= notice
%h3 S2AB
#s2admin-contents-layout
  .row
  .col-md-12.btn-create
    = button_to 'CREATE TEST', new_experiment_path, class: "btn btn-primary", method: :get
  .row
    %div{class: "form-group pull-right"}
      %input{type:"text", class:"search form-control", placeholder:"search", autofocus: true}
    %span{class: "counter pull-right"}
    %table.table.table-hover.tablesorter.results
      %thead
        %th ID
        %th SERVICE NAME
        %th TEST NAME
        %th DESCRIPTION
        %th TEST TYPE
        %th TOTAL MODULAR
        %th UPDATED BY
        %th UPDATED AT
      %tbody
        - @exps.each do |exp|
          %tr{onClick: "location.href='/experiments/#{exp.id}/detail'", style: "cursor:pointer;"}
            %td= exp.id
            %td{:title => "S2Graph Service Name"}= exp.service_name
            %td= exp.name
            %td= exp.description
            %td{:title => "U:User Based Test/T:Traffic Based Test"}
              = exp.experiment_type
            %td= exp.total_modular
            %td
              = exp.updated_by.presence || exp.created_by.presence || ''
            %td
              = exp.updated_at.present? ? exp.updated_at.strftime("%Y-%m-%d %H:%M") : exp.created_at.present? ? exp.created_at.strftime("%Y-%m-%d %H:%M") : ''
  .row
  .col-md-12.btn-create
    = button_to 'CREATE TEST', new_experiment_path, class: "btn btn-primary", method: :get

app/views/experiments/new.html.haml
%h3 CREATE NEW TEST
#s2admin-form-layout
  = render 'form'
  = link_to 'Back', s2ab_path

app/views/experiments/show.html.haml
%p#notice= notice
.s2admin-content-layout
  %p
    %strong service id:
    = @experiment.service_id
  %p
    %strong service name:
    = @experiment.service_name
  %p
    %strong name:
    = @experiment.name
  %p
    %strong description:
    = @experiment.description
  %p
    %strong type:
    = @experiment.experiment_type
  %p
    %strong total modular:
    = @experiment.total_modular
  .s2admin-content-layout
    = link_to 'Edit', edit_experiment_path(@experiment)
    |
    \#{link_to 'Back', s2ab_path}