config/routes.rb
Rails.application.routes.draw do

  resources :counters
  get 'talk_tabs', to: 'talk_tabs#index'
  # get 'admin/index'

  # get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end


  root to: 'experiments#index'

  resources :column_meta
  resources :label_meta
  resources :services  do
    member do
      put 'access_token', to: 'services#updateAccessToken'
    end
  end

  resources :labels, except: [:update] do
    member do
      post 'add_props_and_indices', to: 'labels#addPropsAndIndices'
    end
  end

  resources :buckets, only: [:new, :create, :edit, :show, :update, :destroy] do
    member do
      put 'copy_bucket', to: 'buckets#copyBucket'
    end
  end
  resources :services
  
  # resources :users, only: [:new, :create, :edit, :update, :destroy]
  resources :users do
    member do
      get :info
    end
  end
  resources :authorities
  resources :s2ml_apps
	resources :s2loader_jobs
  resources :s2admin_demos do
    member do
      get :demo
      get :default_id
    end
  end
  resources :experiments do
    member do
      get :detail
      post :modular
    end
  end

  post 'buckets/validate/request_body', to: 'buckets#validateRequestBody'

  get 'queries/visualize'

  post 'queries/partial_graph', to: 'queries#partialGraph'

  post 'queries/call_graph', to: 'queries#callGraph'

  get 'labels/check/:label_name', to: 'labels#check'

  get 'buckets/check/:impression_id', to: 'buckets#check'

  get 's2graph', to: 'services#index'

  get 's2counter', to: 'counters#index'

  get 'users', to: 'users#index'

  get 'access', to: 'authorities#index'

  get 's2ab', to: 'experiments#index'

  post 's2ab/:access_token/ratio-update-all', to: 'experiments#ratioUpdateAll'

  get 's2ab/:access_token/list(/:experiment_name)', to: 'experiments#list'

  get 's2ml', to: 's2ml_apps#index'

  get 's2ml_apps/:id/disable', to: 's2loader_jobs#disable'

  get 's2ml_apps/:id/enable', to: 's2loader_jobs#enable'

  get 's2loader', to: 's2loader_jobs#index'

  get 's2loader_jobs/:id/test', to: 's2loader_jobs#test'

  get 's2loader_jobs/:id/disable', to: 's2loader_jobs#disable'

  get 's2loader_jobs/:id/enable', to: 's2loader_jobs#enable'

  get 'demos', to: 's2admin_demos#index'

  get 'demos/:id/demo', to: 's2admin_demos#demo'

  get 'demos/update_descriptions', to: 's2admin_demos#update_descriptions'

  get 'demos/s2graph', to: 's2admin_demos#index'

  get 'demos/s2counter', to: 's2admin_demos#demo_counter.html.haml'

  get 'demos/talk-channel', to: 'talk_tabs#index'

  get 'links', to: 'links#list'

  get 'servers', to: 'servers#index'

  put 'servers/:server/:status', to: 'servers#toggle_health'

  get 'servers/load', to: 'servers#high_loads'

  get 'servers/latency', to: 'servers#high_latencies'
end

app/models/authority.rb
class Authority < ActiveRecord::Base
  belongs_to :user
  belongs_to :service
end

app/controllers/authorities_controller.rb
class AuthoritiesController < ApplicationController
  before_action :set_authority, only: [:edit, :update, :destroy]
  before_action :set_active
  before_action :has_authority

  # GET /users
  def index
    @authorities = Authority.joins(:user, :service).select("authorities.*, users.email, services.service_name")
# OR
  end

  # GET /authorities/new
  def new
    @authority = Authority.new
  end

  # GET /authorities/1/edit
  def edit
  end

  # POST /authorities
  def create
    @authority = Authority.new(authority_params)

    if @authority.save
      redirect_to authorities_url, notice: 'Authority was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /authorities/1
  def update
    if @authority.update(authority_params)
      redirect_to authorities_url, notice: 'Authority was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /authorities/1
  def destroy
    @authority.destroy
    redirect_to authorities_url, notice: 'Authority was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_authority
      @authority = Authority.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def authority_params
      params.require(:authority).permit(:user_id, :service_id)
    end

    def set_active
      @active = "admin"
    end

    def has_authority
      if session[:authority] != "master" then
        head :forbidden
      end
    end

end

app/helpers/authorities_helper.rb
module AuthoritiesHelper
end

app/views/authorities/_form.html.haml
= simple_form_for @authority, html: { name: "authority-form", onsubmit: "return validateAuthorityForm()"} do |f|
	= f.error_notification
	.form-wrap
		.form-inputs.form
			= f.association :user, collection: User.order(:email), label_method: :email, value_method: :id, :label => "e-mail", required: true
			= f.association :service, collection: Service.order(:service_name), label_method: :service_name, value_method: :id, :label => "service name", required: true
		.form-actions
			= f.button :submit, :class => 'btn btn-primary'

app/views/authorities/edit.html.haml
%h3 EDIT ACCESS
#s2admin-form-layout
	= render 'form'
	= link_to 'Back', access_path

app/views/authorities/index.html.haml
%p#notice= notice
%h3 ACCESS
.col-md-12.btn-create
  = button_to 'CREATE ACCESS', new_authority_path, class: 'btn btn-primary', method: :get
.row
  %div{class: 'form-group pull-right'}
    %input{type:'text', class:'search form-control', placeholder:'search'}
  %span{class: 'counter pull-right'}
  %table.table.table-hover.tablesorter.results
    %thead
      %tr
        %th ID
        %th USER
        %th SERVICE
        %th
        %th

    %tbody
      - @authorities.each do |authority|
        %tr
          %td= authority.id
          %td= authority.email
          %td= authority.service_name
          %td= link_to '', edit_authority_path(authority), class: 'glyphicon glyphicon-pencil bucket-modify'
          %td= link_to '', authority, :method => :delete, class: 'glyphicon glyphicon-trash bucket-delete', :data => { :confirm => 'Are you sure?' }
.col-md-12.btn-create
  = button_to 'CREATE ACCESS', new_authority_path, class: 'btn btn-primary', method: :get

app/views/authorities/new.html.haml
%h3 CREATE ACCESS
#s2admin-form-layout
	= render 'form'
	= link_to 'Back', access_path